version: '2'

services:
  db:
    build: .docker/db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp-network
  web:
    build: .docker/web
    image: nginx:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./root:/var/www
      - .docker/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wp-network
  php:
    build: .docker/php
    image: php:fpm
    volumes:
      - ./root:/var/www
      - .docker/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
    db_data: